"""Compact per-NPC prompt builder.

Builds prompts targeting ~135 tokens input and ~80 tokens output for
1-3 second response times on Llama 3.2 3B.
"""

from __future__ import annotations

import logging

from orchestrator.engine.npc_knowledge import get_knowledge_for_attitude
from orchestrator.models.npc_agent import ConversationMode, NpcAgentState, NpcAttitude
from orchestrator.prompts.npc_modes import ATTITUDE_INSTRUCTIONS, NPC_MODE_TEMPLATES

logger = logging.getLogger(__name__)

# Token budget targets
MAX_RESPONSE_TOKENS = 80


def build_npc_prompt(
    profile: dict,
    state: NpcAgentState,
    player_message: str,
) -> tuple[str, str]:
    """Build a compact system + user prompt for an NPC conversation.

    Returns:
        (system_prompt, user_prompt) tuple ready for Ollama.

    Token budget:
        System: ~60 (mode template) + ~10 (attitude) + ~30 (knowledge) = ~100
        User: ~15 (player message) + ~20 (context) = ~35
        Total input: ~135 tokens
        Response budget: ~80 tokens
    """
    name = profile.get("name", state.npc_id)
    role = profile.get("role", "person")
    personality = profile.get("dialogue_style") or profile.get("personality", "")

    # Get mode template
    mode_key = state.mode.value
    template = NPC_MODE_TEMPLATES.get(mode_key, NPC_MODE_TEMPLATES["chatting"])
    system_base = template.format(name=name, role=role, personality=personality)

    # Add attitude instruction
    attitude_instruction = ATTITUDE_INSTRUCTIONS.get(state.attitude.value, "")
    system_prompt = f"{system_base}\nAttitude: {attitude_instruction}"

    # Add knowledge facts
    facts = get_knowledge_for_attitude(profile, state.attitude)
    if facts:
        # Limit to 3 most relevant facts to stay within token budget
        limited_facts = facts[:3]
        knowledge_str = " ".join(limited_facts)
        system_prompt += f"\nYou know: {knowledge_str}"

    # Add skill context if present (e.g., "The adventurer just intimidated you successfully")
    if state.skill_context:
        system_prompt += f"\n[{state.skill_context}]"

    # Build user prompt
    user_prompt = f'The adventurer says: "{player_message}"'

    return system_prompt, user_prompt


def build_choices_for_mode(
    mode: ConversationMode,
    profile: dict,
    state: NpcAgentState,
) -> list[str]:
    """Generate deterministic choices based on current conversation mode.

    Choices are NOT generated by the LLM -- they come from the orchestrator
    based on mode and NPC capabilities.
    """
    match mode:
        case ConversationMode.CHATTING:
            choices = _chatting_choices(profile)
        case ConversationMode.BARTERING:
            choices = _bartering_choices(profile)
        case ConversationMode.QUEST_GIVING:
            choices = _quest_choices(profile)
        case ConversationMode.REFUSING:
            choices = _refusing_choices(profile)
        case ConversationMode.RECRUITING:
            choices = _recruiting_choices(profile, state)
        case ConversationMode.WARNING:
            choices = ["Ask for details", "Thank them", "End conversation"]
        case _:
            choices = ["Continue talking", "End conversation"]

    return choices


def _chatting_choices(profile: dict) -> list[str]:
    """Generate chatting choices based on NPC knowledge topics."""
    choices: list[str] = []

    # Extract topics from knowledge tiers or flat knowledge
    knowledge_tiers = profile.get("knowledge_tiers", {})
    if knowledge_tiers:
        # Build topic choices from mode_prompts or quest/barter capabilities
        mode_prompts = profile.get("mode_prompts", {})
        quest_data = profile.get("quest_data")
        if quest_data:
            choices.append(f"Ask about work")
        if mode_prompts:
            choices.append("Ask about the area")
        else:
            choices.append("Ask about the area")
            choices.append("Ask about rumors")
        if not choices:
            choices.append("Ask about the area")
    else:
        choices.append("Ask about the area")
        choices.append("Ask about rumors")

    choices.append("End conversation")
    return choices


def _bartering_choices(profile: dict) -> list[str]:
    """Generate bartering choices from NPC inventory."""
    choices: list[str] = []
    inventory = profile.get("bartering_inventory", [])

    for item in inventory[:3]:
        name = item.get("slug", "item").replace("_", " ")
        price = item.get("price_gp", "?")
        choices.append(f"Buy {name} ({price}gp)")

    choices.append("Sell something")
    choices.append("Leave")
    return choices


def _quest_choices(profile: dict) -> list[str]:
    """Generate quest-related choices."""
    return ["Accept quest", "Ask for details", "Decline"]


def _refusing_choices(profile: dict) -> list[str]:
    """Generate choices when NPC is refusing to talk."""
    choices = ["Try Persuasion", "Try Intimidation", "Walk away"]
    return choices


def _recruiting_choices(profile: dict, state: NpcAgentState) -> list[str]:
    """Generate recruitment choices."""
    dc = profile.get("recruitment_dc", 15)
    return [f"Make your case (Persuasion DC {dc})", "Walk away"]
